"""Add NFT columns to submissions

Revision ID: 3be8a51823ff
Revises: 
Create Date: 2025-11-09 10:32:39.782328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be8a51823ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('nft_mint_address', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('nft_tx_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'nft_tx_hash')
    op.drop_column('submissions', 'nft_mint_address')
    # ### end Alembic commands ###

